"""add tool message columns

Revision ID: 11ee7e0bf90b
Revises: 742d95d1517b
Create Date: 2026-09-01 12:06:42.944059

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11ee7e0bf90b"
down_revision: str | Sequence[str] | None = "742d95d1517b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("tool_call_id", sa.String(length=200), nullable=True, comment="ToolMessage存储的tool_call_id"),
    )
    op.add_column(
        "messages", sa.Column("tool_name", sa.String(length=100), nullable=True, comment="ToolMessage的工具名")
    )
    op.add_column(
        "messages",
        sa.Column(
            "tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="模型声明的工具调用列表"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "tool_calls")
    op.drop_column("messages", "tool_name")
    op.drop_column("messages", "tool_call_id")
    # ### end Alembic commands ###
