"""add run commands table

Revision ID: 2963b6ea91c2
Revises: 4a615be3d0c8
Create Date: 2026-09-23 17:45:07.439995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2963b6ea91c2"
down_revision: str | Sequence[str] | None = "4a615be3d0c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_commands",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="命令唯一标识ID"),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=False, comment="所属运行ID"),
        sa.Column("approval_id", sa.Uuid(as_uuid=False), nullable=True, comment="resume命令对应的审批单ID"),
        sa.Column("kind", sa.String(length=20), nullable=False, comment="start=初次执行, resume=审批恢复"),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="pending=待领取, claimed=已领取, completed=已完成, cancelled=已取消, failed=已失败",
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False, comment="payload的结构版本, 从1开始"),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="命令载荷, 不含身份与授权"
        ),
        sa.Column("claimed_epoch", sa.Integer(), nullable=False, comment="领取任期计数, 每次成功领取加1"),
        sa.Column("delivery_attempt", sa.Integer(), nullable=False, comment="投递尝试计数, 每次成功领取加1"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="命令登记时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="状态变更时间",
        ),
        sa.CheckConstraint("kind IN ('start', 'resume')", name="ck_run_commands_kind"),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'completed', 'cancelled', 'failed')", name="ck_run_commands_status"
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"], ["approvals.id"], name="run_commands_approval_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name="run_commands_run_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_commands_approval_id"), "run_commands", ["approval_id"], unique=False)
    op.create_index(op.f("ix_run_commands_run_id"), "run_commands", ["run_id"], unique=False)
    op.create_index(
        "uq_run_commands_one_active",
        "run_commands",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'claimed')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_run_commands_one_active",
        table_name="run_commands",
        postgresql_where=sa.text("status IN ('pending', 'claimed')"),
    )
    op.drop_index(op.f("ix_run_commands_run_id"), table_name="run_commands")
    op.drop_index(op.f("ix_run_commands_approval_id"), table_name="run_commands")
    op.drop_table("run_commands")
    # ### end Alembic commands ###
