"""add run submit idempotency

Revision ID: 452330c276ae
Revises: 93f7b93d2a09
Create Date: 2026-09-22 15:15:29.955105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "452330c276ae"
down_revision: str | Sequence[str] | None = "93f7b93d2a09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs",
        sa.Column("output_message_id", sa.Uuid(as_uuid=False), nullable=True, comment="运行成功后产生的AIMessage的ID"),
    )
    op.add_column(
        "runs",
        sa.Column("request_id", sa.String(length=64), nullable=True, comment="客户端提交的幂等键, 用于幂等性检查"),
    )
    op.add_column(
        "runs",
        sa.Column(
            "request_fingerprint",
            sa.String(length=64),
            nullable=True,
            comment="提交请求的载荷摘要, 用于识别同幂等键但是不同内容",
        ),
    )
    op.create_index(op.f("ix_runs_output_message_id"), "runs", ["output_message_id"], unique=False)
    op.create_index(
        "uq_runs_request_id", "runs", ["request_id"], unique=True, postgresql_where=sa.text("request_id IS NOT NULL")
    )
    op.create_foreign_key(
        "runs_output_message_id_fkey", "runs", "messages", ["output_message_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("runs_output_message_id_fkey", "runs", type_="foreignkey")
    op.drop_index("uq_runs_request_id", table_name="runs", postgresql_where=sa.text("request_id IS NOT NULL"))
    op.drop_index(op.f("ix_runs_output_message_id"), table_name="runs")
    op.drop_column("runs", "request_fingerprint")
    op.drop_column("runs", "request_id")
    op.drop_column("runs", "output_message_id")
    # ### end Alembic commands ###
