"""add approval run attribution

Revision ID: 4a615be3d0c8
Revises: 452330c276ae
Create Date: 2026-09-23 16:31:02.358964

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a615be3d0c8"
down_revision: str | Sequence[str] | None = "452330c276ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("approvals", sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=True, comment="所属运行ID"))
    # ### end Alembic commands ###

    # uq_runs_thread_id 保证 thread_id 精确映射到唯一运行, 因此可以直接回填
    op.execute("UPDATE approvals a SET run_id = r.id FROM runs r WHERE r.thread_id = a.thread_id AND a.run_id IS NULL")
    # 收紧前先验证回填完整, 存在孤立审批时直接失败, 不留下 NULL 让 SET NOT NULL 报模糊错误
    orphans = op.get_bind().execute(sa.text("SELECT count(*) FROM approvals WHERE run_id IS NULL")).scalar_one()
    if orphans:
        raise RuntimeError(f"{orphans} 条审批无法按 thread_id 映射到运行, 需先补建迁移运行记录再升级")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_foreign_key("approvals_run_id_fkey", "approvals", "runs", ["run_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
    op.alter_column("approvals", "run_id", existing_type=sa.Uuid(as_uuid=False), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("approvals_run_id_fkey", "approvals", type_="foreignkey")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_column("approvals", "run_id")
    # ### end Alembic commands ###
