"""baseline schema

Revision ID: 742d95d1517b
Revises:
Create Date: 2026-08-28 19:33:59.435825

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "742d95d1517b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="用户唯一标识ID"),
        sa.Column("uid", sa.BigInteger(), sa.Identity(always=False, start=10000), nullable=False, comment="用户UID"),
        sa.Column("username", sa.String(length=20), nullable=False, comment="用户名(唯一)"),
        sa.Column("nickname", sa.String(length=50), nullable=True, comment="昵称"),
        sa.Column("password_hash", sa.String(length=200), nullable=False, comment="密码哈希"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="用户注册时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="用户信息更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_uid"), "users", ["uid"], unique=True)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="会话唯一标识ID"),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False, comment="会话所属用户ID"),
        sa.Column("title", sa.String(length=200), nullable=False, comment="会话标题"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="active=进行中, archived=已归档"),
        sa.Column("has_pending_task", sa.Boolean(), nullable=False, comment="是否存在被打断未完成的任务"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="消息唯一标识ID"),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False, comment="所属会话ID"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="user=用户, assistant=模型, system=系统提示词, tool=工具消息",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="消息正文"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
            comment="消息产生时间",
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_session_id"), "messages", ["session_id"], unique=False)
    op.create_table(
        "todos",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="任务唯一标识ID"),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False, comment="所属会话ID"),
        sa.Column("title", sa.String(length=500), nullable=False, comment="任务描述"),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="pending=待执行, in_progress=执行中, done=已完成, failed=执行失败",
        ),
        sa.Column("position", sa.Integer(), nullable=False, comment="任务在计划中的序号"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="任务创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="状态变更时间",
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todos_session_id"), "todos", ["session_id"], unique=False)
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="工具唯一标识ID"),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False, comment="所属会话ID"),
        sa.Column("tool_name", sa.String(length=100), nullable=False, comment="工具名称"),
        sa.Column("tool_call_id", sa.String(length=200), nullable=True, comment="发起该工具调用的tool_call_id"),
        sa.Column("tool_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="工具入参"),
        sa.Column("tool_output", sa.Text(), nullable=True, comment="工具输出"),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="success=成功, error=失败, pending=等待审批, rejected=已拒绝",
        ),
        sa.Column("needs_approval", sa.Boolean(), nullable=False, comment="是否需要审批"),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="开始执行时间",
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True, comment="结束执行时间"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_executions_session_id"), "tool_executions", ["session_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="审批唯一标识ID"),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False, comment="所属会话ID"),
        sa.Column("thread_id", sa.String(length=200), nullable=False, comment="线程ID, 用于中断恢复"),
        sa.Column("tool_execution_id", sa.Uuid(as_uuid=False), nullable=False, comment="关联工具执行ID"),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="pending=待审批, approved=已批准, rejected=已拒绝"
        ),
        sa.Column(
            "scope",
            sa.String(length=20),
            nullable=False,
            comment="one_time=批准这一次, command=始终允许此工具执行此命令, tool=始终允许此工具",
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True, comment="审批时间"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="审批创建时间",
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_execution_id"], ["tool_executions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_session_id"), "approvals", ["session_id"], unique=False)
    op.create_index(op.f("ix_approvals_tool_execution_id"), "approvals", ["tool_execution_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_tool_execution_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_session_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_tool_executions_session_id"), table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index(op.f("ix_todos_session_id"), table_name="todos")
    op.drop_table("todos")
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_users_uid"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
