"""add cancelled to approvals status comment

Revision ID: 8963a5b3a155
Revises: af968931523b
Create Date: 2026-09-21 14:14:06.252249

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8963a5b3a155"
down_revision: str | Sequence[str] | None = "af968931523b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "approvals",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="pending=待审批, approved=已批准, rejected=已拒绝, cancelled=已取消",
        existing_comment="pending=待审批, approved=已批准, rejected=已拒绝",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "approvals",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="pending=待审批, approved=已批准, rejected=已拒绝",
        existing_comment="pending=待审批, approved=已批准, rejected=已拒绝, cancelled=已取消",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
