"""add run admission constraints

Revision ID: 93f7b93d2a09
Revises: 8963a5b3a155
Create Date: 2026-09-22 13:19:33.178581

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93f7b93d2a09"
down_revision: str | Sequence[str] | None = "8963a5b3a155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_approvals_status", "approvals", "status IN ('pending', 'approved', 'rejected', 'cancelled')"
    )
    op.drop_index(op.f("ix_runs_thread_id"), table_name="runs")
    op.create_index(
        "uq_runs_one_active_session",
        "runs",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running', 'waiting_approval')"),
    )
    op.create_index("uq_runs_thread_id", "runs", ["thread_id"], unique=True)
    op.create_check_constraint(
        "ck_runs_status",
        "runs",
        "status IN ('pending', 'running', 'waiting_approval', 'succeeded', 'failed', 'cancelled')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_runs_status", "runs", type_="check")
    op.drop_index("uq_runs_thread_id", table_name="runs")
    op.drop_index(
        "uq_runs_one_active_session",
        table_name="runs",
        postgresql_where=sa.text("status IN ('pending', 'running', 'waiting_approval')"),
    )
    op.create_index(op.f("ix_runs_thread_id"), "runs", ["thread_id"], unique=False)
    op.drop_constraint("ck_approvals_status", "approvals", type_="check")
    # ### end Alembic commands ###
