"""add context compact columns

Revision ID: a2129f403045
Revises: 11ee7e0bf90b
Create Date: 2026-09-02 21:41:27.466031

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2129f403045"
down_revision: str | Sequence[str] | None = "11ee7e0bf90b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="模型返回的usage_metadata元数据"
        ),
    )
    op.add_column("sessions", sa.Column("summary_text", sa.Text(), nullable=True, comment="上下文摘要, None表示未压缩"))
    op.add_column(
        "sessions",
        sa.Column("summary_until_message_id", sa.String(length=200), nullable=True, comment="摘要覆盖的最后一条消息ID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "summary_until_message_id")
    op.drop_column("sessions", "summary_text")
    op.drop_column("messages", "usage")
    # ### end Alembic commands ###
