"""add runs table

Revision ID: af968931523b
Revises: a2129f403045
Create Date: 2026-09-16 20:43:07.769884

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af968931523b"
down_revision: str | Sequence[str] | None = "a2129f403045"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False, comment="运行唯一标识ID"),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False, comment="所属会话ID"),
        sa.Column("thread_id", sa.String(length=200), nullable=False, comment="LangGraph线程ID, 每轮运行一个"),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="pending=排队, running=运行, waiting_approval=待审批, succeeded=成功, failed=失败, cancelled=打断",
        ),
        sa.Column("input_message_id", sa.Uuid(as_uuid=False), nullable=True, comment="触发本轮运行的用户消息ID"),
        sa.Column("attempt", sa.Integer(), nullable=False, comment="同一条输入消息的第几次尝试, 从1开始"),
        sa.Column("error_code", sa.String(length=50), nullable=True, comment="失败时的稳定错误码"),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True, comment="收到打断请求的时间"),
        sa.Column("lease_owner", sa.String(length=100), nullable=True, comment="领取本运行的worker标识"),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True, comment="领取租约的到期时间"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True, comment="进入running状态的时间"),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True, comment="进入终态的时间"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="运行登记时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="状态变更时间",
        ),
        sa.ForeignKeyConstraint(["input_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_input_message_id"), "runs", ["input_message_id"], unique=False)
    op.create_index(op.f("ix_runs_session_id"), "runs", ["session_id"], unique=False)
    op.create_index(op.f("ix_runs_thread_id"), "runs", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runs_thread_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_session_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_input_message_id"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
