"""add tool execution run attribution

Revision ID: ea474dc85816
Revises: 2963b6ea91c2
Create Date: 2026-09-24 17:05:27.067122

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea474dc85816"
down_revision: str | Sequence[str] | None = "2963b6ea91c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool_executions", sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=True, comment="所属运行ID"))
    # ### end Alembic commands ###

    # 工具记录优先通过审批关系映射; 一条记录被多张不同运行的审批指向时无法判定归属
    ambiguous = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT count(*) FROM (SELECT a.tool_execution_id FROM approvals a "
                "JOIN runs r ON r.id = a.run_id GROUP BY a.tool_execution_id HAVING count(*) > 1) t"
            )
        )
        .scalar_one()
    )
    if ambiguous:
        raise RuntimeError(f"{ambiguous} 条工具记录通过审批关系映射到多个运行, 需先人工核对再升级")
    op.execute(
        "UPDATE tool_executions te SET run_id = a.run_id FROM approvals a "
        "WHERE a.tool_execution_id = te.id AND te.run_id IS NULL AND a.run_id IS NOT NULL"
    )
    # 其余历史记录留在 run_id IS NULL 的显式兼容路径, 不按相近时间强行关联也不伪造归属

    # 建唯一索引前查重: 命中说明同一运行内同一逻辑调用已有多条主记录
    duplicates = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT count(*) FROM (SELECT run_id, tool_call_id FROM tool_executions "
                "WHERE run_id IS NOT NULL AND tool_call_id IS NOT NULL "
                "GROUP BY run_id, tool_call_id HAVING count(*) > 1) t"
            )
        )
        .scalar_one()
    )
    if duplicates:
        raise RuntimeError(f"{duplicates} 组 (run_id, tool_call_id) 已有重复记录, 需先人工核对再升级")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_tool_executions_run_id"), "tool_executions", ["run_id"], unique=False)
    op.create_foreign_key(
        "tool_executions_run_id_fkey", "tool_executions", "runs", ["run_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        "uq_tool_execution_call",
        "tool_executions",
        ["run_id", "tool_call_id"],
        unique=True,
        postgresql_where=sa.text("run_id IS NOT NULL AND tool_call_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tool_executions_run_id_fkey", "tool_executions", type_="foreignkey")
    op.drop_index(
        "uq_tool_execution_call",
        table_name="tool_executions",
        postgresql_where=sa.text("run_id IS NOT NULL AND tool_call_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_tool_executions_run_id"), table_name="tool_executions")
    op.drop_column("tool_executions", "run_id")
    # ### end Alembic commands ###
